### ISSUE TITLE
HCSR04 on BeagleBone doesn't work

### ISSUE THREAD

**Issue by asuar078** [mattjlewis/diozero#16] opened 2017-03-06 22:27 UTC
Hello, I was trying to use the HCSR04 sensor on the beaglebone black (Debian wheezy kernel 3.8.13-bone80) but I keep getting the same error. 

> 20:40:01.741 [main] ERROR com.diozero.HCSR04.getDistanceCm - Timeout exceeded waiting for echo to go high

A quick look on my scope showed the issue to be that the trigger pin isn't creating a 10us pulse, instead, the pulse seems to be much larger ranging from 50-100us long. 

This is strange since I tried the same sensor on the rpi3 and had no issues. 

Any clues as to where the problem is coming from?

**Comment by asuar078** [comment] 2017-03-06 22:34
Code running 

`try (HCSR04 hcsr04 = new HCSR04(67, 66)) {
            while(true){
                double distance_cm = hcsr04.getDistanceCm();
                System.out.println("Distance : + " + distance_cm + " cm");
            }
        } finally {
            DeviceFactoryHelper.getNativeDeviceFactory().shutdown();
        }`

**Comment by mattjlewis** [comment] 2017-03-11 13:20
Sorry for the delayd response. I'll look into this today / tomorrow. What Java and diozero version are you using?
Matt
 

    On Monday, 6 March 2017, 22:34, Arian Suarez <notifications@github.com> wrote:
 

 Code runningtry (HCSR04 hcsr04 = new HCSR04(67, 66)) { while(true){ double distance_cm = hcsr04.getDistanceCm(); System.out.println("Distance : + " + distance_cm + " cm"); } } finally { DeviceFactoryHelper.getNativeDeviceFactory().shutdown(); }—

**Comment by AsuarLinux** [comment] 2017-03-11 17:50
On the beaglebone I am using java version 1.8.0_77 and the latest diozero that is available on the maven repository which is 0.9.

**Comment by asuar078** [comment] 2017-03-11 17:51
On the beaglebone I am using java version 1.8.0_77 and the latest diozero that is available on the maven repository which is 0.9.

**Comment by mattjlewis** [comment] 2017-03-12 09:17
Ok, I think I know what the problem is. The library defaults to the sysfs provider; I guess it is just too slow. I will create a new wrapper project around this C library (https://github.com/VegetableAvenger/BBBIOlib/tree/master/BBBio_lib) that uses direct memory writes rather than sysfs.
Will let you know once done, won't take long.
Matt
 

    On Saturday, 11 March 2017, 17:52, Arian Suarez <notifications@github.com> wrote:
 

 On the beaglebone I am using java version 1.8.0_77 and the latest diozero that is available on the maven repository which is 0.9.—

**Comment by asuar078** [comment] 2017-03-12 14:51
Sounds great thanks!

**Comment by mattjlewis** [comment] 2017-03-12 21:53
FYI I'm running:Linux beaglebone 4.4.36-ti-r71 #1 SMP Sun Dec 4 02:56:26 UTC 2016 armv7l GNU/Linux
Just committed my changes and pushed a new snapshot build. Note I've not tested it yet, let me know how you get on.
Matt
 

    On Sunday, 12 March 2017, 14:51, Arian Suarez <notifications@github.com> wrote:
 

 Sounds great thanks!—

**Comment by mattjlewis** [comment] 2017-03-12 22:19
And make sure you include diozero-provider-bbbiolib-0.10-SNAPSHOT.jar on the classpath. 

Regards,
Matt

**Comment by asuar078** [comment] 2017-03-15 16:56
Appears to be working, Thanks!

**Comment by mattjlewis** [comment] 2017-03-16 08:26
Excellent, thanks for testing and letting me know.
Matt
 

    On Wednesday, 15 March 2017, 16:56, Arian Suarez <notifications@github.com> wrote:
 

 Appears to be working, Thanks!—

**Closed** 2017-03-16 08:27 UTC
